In [1]:
import numpy as np
import pandas as pd

In [ ]:
data_name = 'heart_disease'
# data_name = 'pendigits'
#data_name = 'vehicle.scale'

#true_value = np.loadtxt(fname='exp_results/true_value_%s.csv'%data_name,  dtype="float", delimiter=",")
# res_ipw3 = np.loadtxt(fname=r'D:\Lab\bandits\cs_ope\cs_ope\experiments\exp_results_095/res_opl_ipw3_%s.csv'%data_name,  dtype="float", delimiter=",")
# res_dm = np.loadtxt(fname=r'D:\Lab\bandits\cs_ope\cs_ope\experiments\exp_results_095/res_opl_dm_%s.csv'%data_name,  dtype="float", delimiter=",")
# res_dml2 = np.loadtxt(fname=r'D:\Lab\bandits\cs_ope\cs_ope\experiments\exp_results_095/res_opl_dml2_sn_%s.csv'%data_name,  dtype="float", delimiter=",")
neulcb = np.loadtxt(fname=r'D:\Lab\bandits\cs_ope\exp_results_0.7_1000\true_res_NLCB_value_satimage.scale.csv',  dtype="float", delimiter=",")

In [4]:
res_ipw3 = res_ipw3[:2]
res_dm = res_dm[:2]
res_dml2 = res_dml2[:2]

In [5]:
res_dml2

array([0.93638557, 0.        ])

In [38]:
res_ipw3 = res_ipw3[:4]
res_dm = res_dm[:4]
res_dml2 = res_dml2[:4]

In [37]:
neulcb=neulcb[:8]

In [33]:
neulcb

array([[0.70999998, 0.81666666, 0.64999998],
       [0.84666669, 0.77999997, 0.68000001],
       [0.81666666, 0.76666665, 0.70999998],
       [0.85666668, 0.83333331, 0.81999999],
       [0.69      , 0.67000002, 0.68000001],
       [0.73666668, 0.76999998, 0.73666668],
       [0.84666669, 0.88      , 0.75      ]])

In [38]:

for i in range(3):
    # mse_dml2 = np.mean(res_dml2)
    # mse_ipw3 = np.mean(res_ipw3)
    # mse_dm = np.mean(res_dm)
    neulcb_rwd = np.mean(neulcb[:,i])
    std_neulcb = np.std(res_dml2[:,i])
    # std_dml2 = np.std(res_dml2)
    # std_ipw3 = np.std(res_ipw3)
    # std_dm = np.std(res_dm)
    
    # print(mse_ipw3)
    
    if i == 0:
        # data = np.array([[mse_dml2, std_dml2, mse_ipw3, std_ipw3, mse_dm, std_dm]])
        data=np.array([[neulcb_rwd,std_neulcb]])
    else:
        data = np.append(data, np.array([[neulcb_rwd,std_neulcb]]), axis=0)

In [39]:
print(np.round(pd.DataFrame(data), 3))

       0      1
0  0.772  0.123
1  0.791  0.121
2  0.727  0.101


In [40]:

result['800']=data[0][[0,2,4]]

In [41]:
result

{'Dataset': ['dml2', 'ipw3', 'dm'],
 '1000': array([0.95148098, 0.37288165, 0.73949881]),
 '800': array([0.93638557, 0.70246845, 0.59827844])}

In [42]:
# print(np.round(pd.DataFrame(data), 3).to_latex())
print(np.round(pd.DataFrame(result), 3))

  Dataset   1000    800
0    dml2  0.951  0.936
1    ipw3  0.373  0.702
2      dm  0.739  0.598


In [ ]:
data_name = 'heart_disease'
N=300
ratio=0.7
true_value = np.loadtxt(fname='exp_results_{ratio}_{N}/true_value_%s.csv'%data_name,  dtype="float", delimiter=",")
res_ipw3 = np.loadtxt(fname='exp_results_{ratio}_{N}/res_ipw3_%s.csv'%data_name,  dtype="float", delimiter=",")
res_dm = np.loadtxt(fname='exp_results_{ratio}_{N}/res_dm_%s.csv'%data_name,  dtype="float", delimiter=",")
res_dml1 = np.loadtxt(fname='exp_results_{ratio}_{N}/res_dml1_%s.csv'%data_name,  dtype="float", delimiter=",")
res_dml2 = np.loadtxt(fname='exp_results_{ratio}_{N}/res_dml2_%s.csv'%data_name,  dtype="float", delimiter=",")
res_dml1_sn = np.loadtxt(fname='exp_results_{ratio}_{N}/res_dml1_sn_%s.csv'%data_name,  dtype="float", delimiter=",")
res_dml2_sn = np.loadtxt(fname='exp_results_{ratio}_{N}/res_dml2_sn_%s.csv'%data_name,  dtype="float", delimiter=",")

FileNotFoundError: exp_results/true_value_heart_disease.csv not found.

In [258]:
for i in range(3):
    mse_dml1 = np.sqrt(np.mean((res_dml1[:,i] - true_value)**2))
    mse_dml2 = np.sqrt(np.mean((res_dml2[:,i] - true_value)**2))
    mse_dml1_sn = np.sqrt(np.mean((res_dml1_sn[:,i] - true_value)**2))
    mse_dml2_sn = np.sqrt(np.mean((res_dml2_sn[:,i] - true_value)**2))
    mse_ipw3 = np.sqrt(np.mean((res_ipw3[:,i] - true_value)**2))
    mse_dm = np.sqrt(np.mean((res_dm[:,i] - true_value)**2))
    
    if i == 0:
        data = np.array([[mse_dml1, mse_dml2, mse_dml1_sn, mse_dml2_sn, mse_ipw3, mse_dm]])
    else:
        data = np.append(data, np.array([[mse_dml1, mse_dml2, mse_dml1_sn, mse_dml2_sn, mse_ipw3, mse_dm]]), axis=0)

In [259]:
print(np.round(pd.DataFrame(data), 3).to_latex())

\begin{tabular}{lrrrrrr}
\toprule
{} &      0 &      1 &      2 &      3 &       4 &      5 \\
\midrule
0 &  0.305 &  0.305 &  0.405 &  0.406 &   4.560 &  0.202 \\
1 &  0.272 &  0.257 &  0.421 &  0.416 &  20.251 &  0.369 \\
2 &  0.335 &  0.381 &  0.579 &  0.589 &  10.267 &  0.582 \\
\bottomrule
\end{tabular}



In [25]:
res_ipw3

array([[0.34615803, 0.35732443, 0.38830912],
       [0.29549086, 0.289192  , 0.1905642 ],
       [0.3305948 , 0.35494564, 0.16973971],
       [0.28548532, 0.33828547, 0.31193576],
       [0.36382171, 0.35632439, 0.2676066 ],
       [0.26758493, 0.3176647 , 0.26969643],
       [0.30860962, 0.32912474, 0.31141428],
       [0.23763304, 0.2707934 , 0.25009973],
       [0.27609476, 0.3978576 , 0.        ],
       [0.        , 0.        , 0.        ]])

In [170]:
2350000000 < 1490000000

False